# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(default='', max_length=15, unique=True)),
                ('password', models.CharField(default='', max_length=32)),
                ('nick', models.CharField(default='', max_length=50)),
                ('photo', models.TextField(default='')),
                ('signature', models.TextField(default='')),
                ('sex', models.CharField(default='', max_length=10)),
                ('latitude', models.CharField(default='0', max_length=32)),
                ('longitude', models.CharField(default='0', max_length=32)),
                ('curbind', models.IntegerField(default=0)),
                ('lastbind', models.TextField(default='')),
            ],
        ),
    ]
